### ISSUE TITLE
Won't generate schmea.sql for MySQL 8

### ISSUE THREAD

**Issue by Aunmag** [amacneil/dbmate#313]
dbmate doesn't generate `schmea.sql` (my `./db/schema.sql` stays empty), while everything else works fine

My `docker-compose.yml`:
```yml
version: '3'

services:
  db:
    image: mysql:8.0
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db/inner/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_ROOT}"

  db-migrations:
    depends_on:
      - db
    image: amacneil/dbmate:1.15
    volumes:
      - ./db/migrations/:/opt/db/migrations/
      - ./db/schema.sql:/opt/db/schema.sql
    entrypoint: ["dbmate", "-d", "/opt/db/migrations/", "-s", "/opt/db/schema.sql", "-u", "mysql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}", "--wait", "up"]
```

Run:
```sh
docker compose build
docker compose run
```

Says:
```log
[+] Running 3/2
 - Network mta-server_default            Created                                                                                                                                                                                                                          0.7s 
 - Container mta-server-db-1             Created                                                                                                                                                                                                                          0.1s
 - Container mta-server-db-migrations-1  Created                                                                                                                                                                                                                          0.1s
Attaching to mta-server-db-1, mta-server-db-migrations-1
mta-server-db-1             | 2022-08-09 16:55:05+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.30-1.el8 started.
mta-server-db-1             | 2022-08-09 16:55:05+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mta-server-db-1             | 2022-08-09 16:55:05+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.30-1.el8 started.
mta-server-db-1             | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mta-server-db-1             | 2022-08-09T16:55:05.514030Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mta-server-db-1             | 2022-08-09T16:55:05.518043Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.30) starting as process 1
mta-server-db-1             | 2022-08-09T16:55:05.521751Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mta-server-db-1             | 2022-08-09T16:55:05.551886Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mta-server-db-1             | 2022-08-09T16:55:07.723229Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mta-server-db-1             | 2022-08-09T16:55:10.255933Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mta-server-db-1             | 2022-08-09T16:55:10.256263Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mta-server-db-1             | 2022-08-09T16:55:10.266916Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mta-server-db-1             | 2022-08-09T16:55:10.584804Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mta-server-db-1             | 2022-08-09T16:55:10.584864Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
mta-server-db-migrations-1  | Waiting for database.....
mta-server-db-migrations-1  | Applying: 20220809153010_initial.sql
mta-server-db-migrations-1 exited with code 0
```
