### ISSUE TITLE
DBMate always delets my database anytime I run a migration

### ISSUE THREAD

**Issue by livingforjesus** [amacneil/dbmate#551]
**Description**
Anytime I run dbmate migrate, my db data is cleared

- Version: 2.16.0
- Database: Postgres
- Operating System: Macos(but it runs on github actions)

**Steps To Reproduce**

```
name: Run migration

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install DBmate
        run: |
          sudo curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo chmod +x /usr/local/bin/dbmate

      - name: Run Migrations
        run: |
          dbmate -d ./database/migration --url "postgresql://postgres:postgres@***:5432/app" migrate

```

**Expected Behavior**
My db data stays the same
