### ISSUE TITLE
Supporting Postgres 17

### ISSUE THREAD

**Issue by ShahriarKh** [amacneil/dbmate#594]
When I want to run `dbmate dump` against a Postgres 17 database, `pg_dump` complains about version mismatch:
```
Error: pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.0; pg_dump version: 16.4
```

- Version: 2.23.0
- Database: postgres:17-alpine
- Operating System: docker on wsl on windows 11

**Comment by amacneil** [comment]
We don't bundle pg_dump, that old version is installed on your machine

**Comment by ShahriarKh** [comment]
Hmm... but running `pg_dump` in wsl gives me:
```bash
Command 'pg_dump' not found, but can be installed with:
sudo apt install postgresql-client-common
```

I assumed it might be some problem with alpine & tried with another image (`postgres:17` debian), but still get the same error:
```bash
Error: pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 17.0 (Debian 17.0-1.pgdg120+1); pg_dump version: 16.4
```

It works with v16 images like `postgres:16-alpine`

So, where is `pg_dump` coming from? If it's my machine, running the command should show it. If it's the postgres image, I don't really think there would be a version mismatch in official images! also, if I run the `pg_dump` inside the container directly (without using dbmate) it works:
```yaml
services:
  db:
    container_name: dbcontainer 
    image: postgres:17-alpine
    env_file: ./db/.env
    ports:
      - 9999:5432
```
```bash
docker exec dbcontainer pg_dump -U postgres
```
```bash
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--
```

So, I guess what's raising this issue is this:
https://github.com/amacneil/dbmate/blob/9594248d266967e07e49627c8134e9ea3197fe87/Dockerfile#L13
or this:
https://github.com/amacneil/dbmate/blob/9594248d266967e07e49627c8134e9ea3197fe87/Dockerfile#L34

**Comment by dossy** [comment]
@ShahriarKh Can you give us a full reproduction of the issue?  How are you installing dbmate?  How are you running it?

The shell in which you execute `dbmate` must have a v16.4 `pg_dump` binary in `$PATH` that `dbmate` is using.

In that same shell, could you execute `type -a pg_dump` and share the output with us here?

**Comment by ShahriarKh** [comment]
Both postgres and dbmate are run with docker. Here's my docker compose file:
```yaml
services:
  db:
    container_name: my-db
    # restart: 'always'
    image: postgres:17-alpine
    env_file: ./db/.env
    ports:
      - 9999:5432
    volumes:
      - pg17:/var/lib/postgresql/data
      
  dbmate:
    container_name: my-dbmate
    image: ghcr.io/amacneil/dbmate:latest
    depends_on:
      - db
    entrypoint: ['sh'] # or ['dbmate']
    env_file: ./db/.env
    volumes:
      - ./db/:/db/

volumes:
  pg17:
```

And here are the results of running `type -a pg_dump`:

wsl:
```
type -a pg_dump
> -bash: type: pg_dump: not found
```

postgres in docker:
```
docker exec -it my-db bash
type -a pg_dump
> pg_dump is /usr/local/bin/pg_dump
```

pgmate in docker:
```
docker compose run -it dbmate
type -a pg_dump
> /usr/bin/pg_dump
```
