### ISSUE TITLE
ENV variable oddities

### ISSUE THREAD

**Issue by safaci2000** [amacneil/dbmate#653]
**Description**

Seems like there some precedence with the ENV Loading that happens that breaks the expected behavior.

- Version: ghcr.io/amacneil/dbmate:2.27
- Database: postgres:17.2-alpine 
- Operating System: Linux, Ubuntu 22.04.5 LTS 

**Steps To Reproduce**

Previous config:
```yaml
  db-migrate:
    env_file: .env
    networks:
      - funcap-backend
    image: ghcr.io/amacneil/dbmate:2.27
    volumes:
      - ./db:/db
```

docker compose run db-migrate up 
Error: invalid url, have you set your --url flag or DATABASE_URL environment variable?

Dot Env
```sh
POSTGRES_USER=ht_controller_user
POSTGRES_PASSWORD=xxxx
DATABASE_URL="postgres://ht_controller_user:xxx@db:5432/funcap_controller?sslmode=disable"
POSTGRES_DB=funcap_controller
DB_HOST=db
DB_PORT=5432
OTEL_SERVICE_NAME=funcap-staging


DB01_TYPE=postgres
DB01_NAME=funcap_controller
DB01_USER=ht_controller_user
DB01_PASS="xxx"
DB01_BACKUP_INTERVAL=1440
DB01_BACKUP_BEGIN=0000
DB01_CHECKSUM=SHA1
CONTAINER_ENABLE_MONITORING=FALSE
DB01_SPLIT_DB=FALSE

DB01_COMPRESSION=GZ
DB01_BACKUP_LOCATION=S3
DB01_S3_BUCKET=ht-controller-backup-staging
DB01_S3_KEY_ID=xxx
DB01_S3_KEY_SECRET=xxxxxx
DB01_S3_PATH=staging/postgres
DB01_S3_REGION=us-east-1
DB01_S3_HOST=ceph.lb.es.net
DB01_S3_PROTOCOL=https
DB01_S3_CERT_SKIP_VERIFY=TRUE
DB01_CLEANUP_TIME=10080



SN_P4_AUTH_TOKEN=xxxxx
SQL_DEBUG=0
```

On the other hand if I rename DATABASE_URL to APP_DATABASE_URL in my .env file and use:

```yaml
  db-migrate:
#    env_file: .env
    networks:
      - funcap-backend
    image: ghcr.io/amacneil/dbmate:2.27
    environment:
      DATABASE_URL: $MIGRATION_URL
    volumes:
      - ./db:/db
```

That works fine

**Expected Behavior**

To use the value of DATABASE_URL to perform the DB Migration.
