### ISSUE TITLE
Issue with Postgres Connection String

### ISSUE THREAD

**Issue by joshdavey** [amacneil/dbmate#83]
Hey, I'm trying to run `docker-compose run dbmate new test` but I'm getting the following error: 

```
Error: parse "postgres://postgres:password@127.0.0.1:5432/dbname?sslmode=disable": first path segment in URL cannot contain colon
```

I'm setting the database URL using the DATABASE_URL env variable and am using the `amacneil/dbmate` docker image.

I added dbmate as a service to my docker-compose file which looks like this:
```
  dbmate:
    image: amacneil/dbmate
    depends_on:
      - database
    env_file:
      - docker.env
    volumes:
      - ./db/migrations:/db/migrations
```

Thanks
